### ISSUE TITLE
No such file or directory: 'C:\\Users\\Jerry\\.tidepredict\\stations.csv'

### ISSUE THREAD

**Issue by slowtoaccept** [windcrusader/tidepredict#10]
(tidepredict) λ python tidepredict -l Lyttelton
Refreshing stations list from online source.
ftp request:RETR /uhslc/rqds/pacific/pacific.lst
ftp request:RETR /uhslc/rqds/indian/indian.lst
ftp request:RETR /uhslc/rqds/atlantic/atlantic.lst
Traceback (most recent call last):
  File "tidepredict\__main__.py", line 66, in process_args
    stations = pd.read_csv(constants.STATIONFILE)
  File "C:\Users\Jerry\New_Python_Projects\tidepredict\lib\site-packages\pandas\io\parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Jerry\New_Python_Projects\tidepredict\lib\site-packages\pandas\io\parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\Jerry\New_Python_Projects\tidepredict\lib\site-packages\pandas\io\parsers.py", line 936, in __init__
    self._make_engine(self.engine)
  File "C:\Users\Jerry\New_Python_Projects\tidepredict\lib\site-packages\pandas\io\parsers.py", line 1168, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\Jerry\New_Python_Projects\tidepredict\lib\site-packages\pandas\io\parsers.py", line 1998, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Jerry\\.tidepredict\\stations.csv'

**Comment by windcrusader** [comment]
Thanks for reporting this it should be fixed now through 4808c69
