### ISSUE TITLE
string index out of range, error when generating data for "La Jolla"

### ISSUE THREAD

**Issue by dlarue** [windcrusader/tidepredict#9]
$ python tidepredict -harmgen -l "La Jolla"
ftp request:RETR /uhslc/rqds/pacific/hourly/h554a.zip
Opening data file:i554a15.dat
Traceback (most recent call last):
  File "/home/dlarue/miniconda3/envs/envPyTides/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dlarue/miniconda3/envs/envPyTides/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "tidepredict/__main__.py", line 183, in <module>
    process_args(args)
  File "tidepredict/__main__.py", line 99, in process_args
    loc_code = loc_code)
  File "/home/dlarue/tidepredict/tidepredict/processdata.py", line 179, in process_unhw_data
    if dateraw[8] == "1":
IndexError: string index out of range

**Comment by windcrusader** [comment]
Thanks for this. I can replicate the bug and I'm working on a fix.

**Comment by windcrusader** [comment]
Fixed in b88be7a
